name: Hello World Workflow

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions!"
